### ISSUE TITLE
Developer Beta Release Requirements

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#237]
- [ ] **Email To MetaMask List**
   - [ ] [Copy in google docs](https://docs.google.com/document/d/1lzkS0WJn4l_ZQhKb6zLnVpZLmphGU98utZxx1D1R_sI/edit)
     - [ ] @kennyrowe has added a few comments
     - [ ] @flyswatter  to send copy to ethereum.net editor in chief
   - [ ] Send on **June 20th**
     - [ ] Access to mail chimp 
   - [ ] Build HTML for email
     - [ ] @frankiep may be able to lend a hand
     - [ ] @vladt can help with design, not HTML
   - [ ] Define CTA
     - [ ] Download MetaMask Now
   - [ ] Assets needed
     - [ ] Video
     - [ ] Imagery (logo)
     - [ ] Possibly accumulate other example of similar emails?

 ---
 - [ ] **Dev Resources for launch**
   - [ ] https://github.com/MetaMask/compat-guide

 ---
 - [ ] **Videos**
   - [ ] 30 second vid
   - [ ] 3 min vid

 ---
 - [ ] **Consensys Newsletter Copy**
   - [ ] Coordinate with coms team (Most likely Rebecca)
     - [ ] Target June 22nd Newsletter

 ---
 - [ ] **Reddit Post (Ethereum sub)**
   - [ ] Landing page
   - [ ] Follow up on comments

 ---
 - [ ] **Website**
   - [ ] Launch ASAP
   - [ ] Update (May 31st): 
     - [ ] @gbugyis's top priority ATM is uPort fixes
     - [ ] @kennyrowe will review to-do list https://github.com/metamask/landing/issues and add any that was overlooked
     - [ ] @kennyrowe will follow up with @gbugyis next week (June 6th for a status update)
     - [ ] @kennyrowe will also make any easy fixes and do a pull request

 ---
 - [ ] **Chrome Store Assest**
   - [ ] Screen Shots
   - [ ] Video ?
   - [ ] Reviews
   - [ ] Copy

 ---
 - [ ] **Other Ideas**
   - [ ] Coordinate a release with dapps on ethercast
     - [ ] Reach out to Joris after he's back from vacation
